[package]
name = "bittorent-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
nanoid = "0.4.0"
reqwest = { version = "0.12.25", default-features = false, features = ["rustls-tls"]}
sha1 = "0.10.6"
tokio = { version = "1.48.0", features = ["full"] }

